# Autogenerated wrapper script for libmodplug_jll for i686-linux-gnu
export libmodplug

## Global variables
PATH = ""
LIBPATH = ""
LIBPATH_env = "LD_LIBRARY_PATH"

# Relative path to `libmodplug`
const libmodplug_splitpath = ["lib", "libmodplug.so"]

# This will be filled out by __init__() for all products, as it must be done at runtime
libmodplug_path = ""

# libmodplug-specific global declaration
# This will be filled out by __init__()
libmodplug_handle = C_NULL

# This must be `const` so that we can use it with `ccall()`
const libmodplug = "libmodplug.so.1"


"""
Open all libraries
"""
function __init__()
    global prefix = abspath(joinpath(@__DIR__, ".."))

    # Initialize PATH and LIBPATH environment variable listings
    global PATH_list, LIBPATH_list
    global libmodplug_path = abspath(joinpath(artifact"libmodplug", libmodplug_splitpath...))

    # Manually `dlopen()` this right now so that future invocations
    # of `ccall` with its `SONAME` will find this path immediately.
    global libmodplug_handle = dlopen(libmodplug_path)
    push!(LIBPATH_list, dirname(libmodplug_path))

    # Filter out duplicate and empty entries in our PATH and LIBPATH entries
    filter!(!isempty, unique!(PATH_list))
    filter!(!isempty, unique!(LIBPATH_list))
    global PATH = join(PATH_list, ':')
    global LIBPATH = join(LIBPATH_list, ':')

    # Add each element of LIBPATH to our DL_LOAD_PATH (necessary on platforms
    # that don't honor our "already opened" trick)
    #for lp in LIBPATH_list
    #    push!(DL_LOAD_PATH, lp)
    #end
end  # __init__()

